jobs:
  - name: job-vr1
    type: manifest
    steps:
      - IN: vr-img1
      #- IN: vr-ecs-opts1
        pull: true
     
      
  
  - name: job-vr2
    type: manifest
    steps:
      - IN: vr-img3
        pull: false
      - IN: vr-dv-opts2
     
      
      
  - name: job-ddc-deploy-vr
    type: deploy
    steps:
    
      - IN: job-vr1
      - IN: vr-ddc-cluster
      
  - name: job-ecs-deploy-vr
    type: deploy
    steps:
     
      - IN: job-vr1
      - IN: vr-ecs-opts1
      - IN: vr-aws-cluster2
      - TASK: managed
        deployMethod: upgrade
        
